image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  tags:
    - prod
  script:
    - mvn compile
  cache:
    paths:
      - ./target
      - ./.m2

test:
  stage: test
  tags:
    - prod
  script:
    - echo 'test'
#    - mvn test

package:
  stage: package
  tags:
    - prod
  script:
    - echo 'package'
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2

deploy:
  stage: deploy
  image: docker
  tags:
    - prod
  script:
    - docker build -t filkoof/zerone_mailing .
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker push filkoof/zerone_mailing:latest1
