image: maven:latest

stages:
  - build
  - test
  - package

build:
  stage: build
  tags:
    - prod
  script:
    - echo 'build'
    - mvn compile
  cache:
    paths:
      - ./target
      - ./.m2

test:
  stage: test
  tags:
    - prod
  script:
    - echo 'test'
#    - mvn test

package:
  stage: package
  tags:
    - prod
  script:
    - echo 'package'
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2